-- CreateEnum
CREATE TYPE "JobType" AS ENUM ('INITIATE_CONVERSATION', 'FOOD_CONSULTATION', 'EXERCISE_GUIDE', 'REMINDING_SLEEP', 'HYDRATION_REMINDING', 'STRESS_MINDFULNESS', 'WORK_LIFESTYLE_ADVICE', 'CHECKUP_MONITORING', 'MOTIVATION_STYLE');

-- CreateTable
CREATE TABLE "Job" (
    "id" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "jobType" "JobType" NOT NULL,
    "message" TEXT NOT NULL,
    "sendDate" TIMESTAMP(3) NOT NULL,
    "isSent" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Job_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Job_id_key" ON "Job"("id");

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
